- name: Create Azure Apache VM Prueba
  hosts: localhost
  connection: local
    
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: lab06
      location: eastus
  
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: lab06
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  
  - name: Add subnet
    azure_rm_subnet:
      resource_group: lab06
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  
  - name: Create public IP address Web01
    azure_rm_publicipaddress:
      resource_group: lab06
      allocation_method: Dynamic
      domain_name_label: web1lab06
      name: myPublicIP1
  
  - name: Create public IP address Web02
    azure_rm_publicipaddress:
      resource_group: lab06
      allocation_method: Dynamic
      domain_name_label: web2lab06
      name: myPublicIP2
  
  - name: Create public IP address LB
    azure_rm_publicipaddress:
      resource_group: lab06
      allocation_method: Dynamic
      domain_name_label: lblab06
      name: myPublicIPLB
  
  - name: Create an availability set for managed disk vm
    azure_rm_availabilityset:
      name: avs-lab06
      resource_group: lab06
      platform_update_domain_count: 5
      platform_fault_domain_count: 2
      sku: Aligned            
  
  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: lab06
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
  
  - name: Create virtual network interface card web01
    azure_rm_networkinterface:
      resource_group: lab06
      name: myNICWeb01
      virtual_network_name: myVnet
      subnet_name: mySubnet
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: myPublicIP1
          primary: True
      security_group: myNetworkSecurityGroup  
  
  - name: Create virtual network interface card web02
    azure_rm_networkinterface:
      resource_group: lab06
      name: myNICWeb02
      virtual_network_name: myVnet
      subnet_name: mySubnet
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: myPublicIP2
          primary: True
      security_group: myNetworkSecurityGroup  

  - name: Create VM Web01
    azure_rm_virtualmachine:
      resource_group: lab06
      name: myWeb01
      vm_size: Standard_B1ms
      admin_username: jcubillos555
      admin_password: Proviteq.1999
      ssh_password_enabled: true
      append_tags: True
      tags:
        env: "Applab06"
      network_interfaces: myNICWeb01
      availability_set: avs-lab06
      managed_disk_type: Standard_LRS
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest        

  - name: Create VM Web02
    azure_rm_virtualmachine:
      resource_group: lab06
      name: myWeb02
      vm_size: Standard_B1ms
      admin_username: jcubillos555
      admin_password: Proviteq.1999
      ssh_password_enabled: true
      append_tags: True
      tags:
        env: "Applab06"
      network_interfaces: myNICWeb02
      availability_set: avs-lab06
      managed_disk_type: Standard_LRS
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest 

  - name: create load balancer
    azure_rm_loadbalancer:
      resource_group: lab06
      name: mylb
      frontend_ip_configurations:
        - name: frontendipconf0
          public_ip_address: myPublicIPLB
      backend_address_pools:
        - name: backendaddrpool0
      probes:
        - name: prob0
          port: 80
      load_balancing_rules:
        - name: lbrbalancingrule0
          frontend_ip_configuration: frontendipconf0
          backend_address_pool: backendaddrpool0
          frontend_port: 80
          backend_port: 80
          probe: prob0
      inbound_nat_rules:
        - name: inboundnatrule0
          backend_port: 8080
          protocol: Tcp
          frontend_port: 8080
          frontend_ip_configuration: frontendipconf0
